---
title: "SentimentAnalysis"
author: "Anugya"
date: "1/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadPackages}
library(tidytext)
sentiments
```

```{r}
#3 commonly used lexicons are:- AFINNS, bing, loughran

get_sentiments("bing")
```

```{r}
library(janeaustenr)
library(stringr)
library(tidytext)
library(tidyverse)

tidy_data <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(), 
         chapter = cumsum(str_detect(text, regex("^chapter[\\divxlc]",
                                                 ignore_case = TRUE)))) %>%
  ungroup() %>%
  unnest_tokens(word, text)

positive_senti <- get_sentiments("bing") %>%
  filter(sentiment == "positive")

tidy_data %>%
  filter(book == "Emma") %>%
  semi_join(positive_senti) %>%
  count(word, sort = TRUE)

library(tidyr)
bing <- get_sentiments("bing")
Emma_senti <- tidy_data %>%
  inner_join(bing) %>%
  count(book = "Emma", index = linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

library(ggplot2)
ggplot(Emma_senti, aes(index, sentiment, fill = book)) + 
  geom_bar(stat = "identity", show.legend = TRUE) + 
  facet_wrap(~book, ncol = 2, scales = "free_x")
```
``` {r}
#counting most common positive and negative sentiments
counting_words <- tidy_data %>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE)
head(counting_words)

```

```{r}
#visualize sentiment scores
counting_words %>%
  filter(n > 150) %>%
  mutate(n = ifelse(sentiment == "negative", -n, n)) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word,n,fill = sentiment)) + 
  geom_col() + 
  coord_flip() +
  labs(y = "Sentiment Score")

```

```{r}
#create word cloud to delineate most recurring positive and negative words
library(reshape2)
library(wordcloud)

tidy_data %>%
  inner_join(bing) %>%
  count(word, sentiment, sort = TRUE) %>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("red", "dark green"), max.words = 100)

```
